services:
  db:
    image: postgres:16
    container_name: booking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - booking_db_data:/var/lib/postgresql/data
volumes:
  booking_db_data:
